version: "3"
 
services:
  openproject:
    image: openproject/community:11
    restart: always
    ports:
     - "8083:80"
    networks:
      - devnet
    volumes:
      - /home/jacinto/DevOps/openproject:/var/openproject/pgdata
      - /home/jacinto/DevOps/openproject:/var/openproject/assets
    environment:
     - SECRET_KEY_BASE=Conoce!2020
  
networks:
  devnet:
    driver: bridge
