apiVersion: v1
kind: ConfigMap
metadata:
  name: kb-server-config
data:
  ELASTIC_VERSION: 7.8.0
  postgres_user: 'postgres'
  postgres_password: 'postgres'
  elastic_host: server-elasticsearch
  elastic_port: '9200'
  elastic_hosts: '["http://server-elasticsearch:9200"]'
  elastic_discovery_type: single-node
  elastic_username: elastic
  elastic_password: changeme
  elastic_security: 'true'
  logstash_monitoring_elasticsearch_hosts: http://server-elasticsearch:9200
  logstash_monitoring_enabled: 'true'
  alertmanager_yml: '/etc/alertmanager/alertmanager.yml'
  zookeeper_client_port: '2181'
  kafka_broker_id: '1'
  kafka_zookeeper_connect: server-zookeeper:2181
  kafka_advertised_listeners: PLAINTEXT://server-kafka:9092
  kafka_listener_protocol_map: PLAINTEXT:PLAINTEXT
  kafka_inter_broker_listener_name: PLAINTEXT
  kafka_offsets_topic_replication_factor: '1'
  kafka_allow_plaintext_listener: 'yes'
  zookeeper_allow_anonymous_login: 'yes'
  prometheus_yml_location: /etc/prometheus/prometheus.yaml
  alert_manager_yml_location: /etc/alertmanager/config.yml
  grafana_security_admin_password: admin
  grafana_users_allow_sign_up: 'false'
  grafana_log_mode: console file
  grafana_server_domain: server-grafana
      
