##################################################################################################
# Kibana service
##################################################################################################
apiVersion: v1  
kind: Service  
metadata:  
  name: edis-kibana  
  labels:  
    app: edis-logs-kibana
    service: kibana 
spec:  
  type: LoadBalancer
  selector:  
    app: edis-logs-kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  clusterIP: 10.96.1.124  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edis-logs-kibana-system
  labels:
    account: logs-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edis-logs-kibana
  labels:
    app: edis-logs-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edis-logs-kibana
  template:
    metadata:
      labels:
        app: edis-logs-kibana
    spec:
      serviceAccountName: edis-logs-kibana-system
      volumes:
      - name: kibana-config
        hostPath:
          path: /home/jacinto/kibana-config/
          type: DirectoryOrCreate
      - name: filebeat-data
        hostPath: 
          path: /home/jacinto/filebeat-data
          type: DirectoryOrCreate
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kb-edis-config
              key: elastic_hosts
        - name: KIBANA_ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kb-edis-config
              key: elastic_hosts
        - name: KIBANA_ELASTICSEARCH_PORT
          valueFrom:
            configMapKeyRef:
              name: kb-edis-config
              key: elastic_port
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: kb-edis-config
              key: elastic_username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kb-edis-config
              key: elastic_password
        name: kibana
        image: docker.elastic.co/kibana/kibana:7.8.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
      initContainers:
      - name: init-elasticsearch
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup edis-elasticsearch.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo esperando a elasticsearch; sleep 2; done"]