##################################################################################################
# alertmanager service
##################################################################################################
apiVersion: v1  
kind: Service  
metadata:  
  name: server-alertmanager  
  labels:  
    app: server-alertmanager
    service: alertmanager 
spec:  
  type: LoadBalancer
  selector:  
    app: server-alertmanager
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  clusterIP: 10.96.1.127
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-monitoring
  labels:
    account: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-alertmanager
  labels:
    app: server-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-alertmanager
  template:
    metadata:
      labels:
        app: server-alertmanager
    spec:
      serviceAccountName: server-monitoring
      volumes:
      - name: alertmanager-dir
        hostPath:
          # directory location on host
          path: ./alert-manager
          # this field is optional
          type: Directory
      containers:
      - env:
        - name: --config.file
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: alert_manager_yml_location
        name: alertmanager
        image: prom/alertmanager
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-dir
          mountPath: /etc/alertmanager/