##################################################################################################
# node-exporter service
##################################################################################################
apiVersion: v1  
kind: Service  
metadata:  
  name: server-node-exporter  
  labels:  
    app: server-node-exporter
    service: node-exporter 
spec:  
  type: LoadBalancer
  selector:  
    app: server-node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
  clusterIP: 10.96.1.129
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-monitoring
  labels:
    account: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-node-exporter
  labels:
    app: server-node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-node-exporter
  template:
    metadata:
      labels:
        app: server-node-exporter
    spec:
      serviceAccountName: server-monitoring
      containers:
      - name: node-exporter
        image: prom/node-exporter
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100