##################################################################################################
# Zookeeper service
##################################################################################################
apiVersion: v1  
kind: Service  
metadata:  
  name: server-zookeeper  
  labels:  
    app: server-events-zookeeper
    service: zookeeper 
spec:  
  type: LoadBalancer
  selector:  
    app: server-events-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  clusterIP: 10.96.1.125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-events-zookeeper-system
  labels:
    account: events-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-events-zookeeper
  labels:
    app: server-events-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-events-zookeeper
  template:
    metadata:
      labels:
        app: server-events-zookeeper
    spec:
      serviceAccountName: server-events-zookeeper-system
      containers:
      - env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: zookeeper_client_port
        - name: ALLOW_ANONYMOUS_LOGIN
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: zookeeper_allow_anonymous_login
        name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181