##################################################################################################
# Kafka service
##################################################################################################
apiVersion: v1  
kind: Service  
metadata:  
  name: server-kafka  
  labels:  
    app: server-events-kafka
    service: kafka 
spec:  
  type: LoadBalancer
  selector:  
    app: server-events-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  clusterIP: 10.96.1.126
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-events-kafka-system
  labels:
    account: events-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-events-kafka
  labels:
    app: server-events-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-events-kafka
  template:
    metadata:
      labels:
        app: server-events-kafka
    spec:
      serviceAccountName: server-events-kafka-system
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_broker_id
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_zookeeper_connect
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_advertised_listeners
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_listener_protocol_map
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_inter_broker_listener_name
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_offsets_topic_replication_factor
        - name: ALLOW_PLAINTEXT_LISTENER
          valueFrom:
            configMapKeyRef:
              name: kb-server-config
              key: kafka_allow_plaintext_listener
        name: kafka
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 9092
      initContainers:
      - name: init-zookeeper
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup server-zookeeper.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo esperando a zookeeper; sleep 2; done"]